version: '2'

services:

  messages-ms:
    container_name: messages-ms
    build: .
    depends_on:
      - messages-db

    links:
      - messages-db

    ports:
      - "4003:4003"

  messages-db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/data/db"
volumes:
   mongodata:
