version: '2'

services:
  mensajes_ms:
    build: ./Docker

    depends_on:
      - mongo_db

    links:
      - mongo_db
        
    ports:
      - "4003:4003"

    tty: true


  mongo_db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/data/db"
volumes:
   mongodata: