version: '2'

services:
  messages-ms:
    build: .
    depends_on:
      - mongo-db

    links:
      - mongo-db
        
    ports:
      - "4003:4003"

    tty: true


  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/data/db"
volumes:
   mongodata:
